"use client";

type StatusTone = "waiting" | "running" | "review" | "completed" | "failed";
type DashboardTaskSummary = Record<StatusTone, number> & { manual?: number; processing?: number };

export type DashboardSnapshot = {
  generatedAt: string;
  system: { worker: { online: boolean }; queue: { waiting: number; running: number }; pipeline: string; killSwitch: { configured: boolean; enabled: boolean } };
  flags: Array<{ name: string; enabled: boolean; configured: boolean }>;
  tasks: DashboardTaskSummary;
  quality: { accept: number; review: number; reject: number; histogram: Record<string, number>; trend: Array<{ date: string; accept: number; review: number; reject: number }> };
  scheduler: { success: number; failed: number; failedReasons: Record<string, number> };
  renderer: { running: number; completed: number; failed: number; averageBatchElapsedSeconds: number | null; recent: Array<{ batchId: string; name: string; status: string; renderedAt: string; outputs: number }> };
  services: Record<string, { name: string; online: boolean; instances: number; status: "online" | "crashed" | "restarting" | "offline"; restartCount: number; lastCrashReason: string | null; lastCrashAt: string | null; lastRestartAt: string | null; nextRestartAt: string | null; waiting: number; running: number; failed: number; retry: number; etaSeconds: number | null }>;
  codex?: { status: string; modelServiceReachable: boolean | null; codexExecutorAlive: boolean | null; sdkTurnActive: boolean; sdkTurnCompleted: boolean; authenticationValid: boolean | null; concurrencyLimit: number; activeSlotCount: number; currentTurn?: { taskKey?: string; service?: string; lastEventAt?: string; startedAt?: string } | null; lastSdkEventAt?: string | null; lastCompletedAt?: string | null; failedRequests?: number; rateLimitErrors?: number; concurrencyErrors?: number; queue?: { waiting?: number; running?: number; failed?: number; retry?: number } };
  recentBatches: Array<{ id: string; name: string; status: string; createdAt: string; updatedAt: string; stage: string; productCount: number; error?: string }>;
};

const labels: Record<string, string> = { uploading: "上传中", reference_queued: "等待样片识别", analyzing_reference: "识别样片中", creating_proxies: "生成分析代理", detecting_products: "识别产品中", regroup_queued: "等待重新分组", reference_ready: "等待确认", batch_queued: "等待剪辑", editing: "剪辑中", review: "待审核", revision_queued: "等待修改", revising: "修改中", cancel_requested: "取消中", canceled: "已取消", completed: "已完成", failed: "人工异常" };

function displayStatus(batch: DashboardSnapshot["recentBatches"][number]) { return labels[batch.status] || batch.status; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(date); }
function isManualBatch(batch: DashboardSnapshot["recentBatches"][number]) { return ["review", "reference_ready", "failed"].includes(batch.status); }
function sortHistogram(histogram: Record<string, number>) { return Object.entries(histogram).sort(([, a], [, b]) => b - a); }

export default function DashboardOverview({ data, loading, onOpenBatch, onCreateBatch, onRefresh }: { data: DashboardSnapshot | null; loading: boolean; onOpenBatch: (id: string) => void; onCreateBatch: () => void; onRefresh: () => void }) {
  if (loading && !data) return <section className="dashboard-loading">正在整理今天的任务…</section>;
  if (!data) return <section className="dashboard-loading">暂时无法读取任务概览，请刷新后重试。</section>;

  const manual = data.recentBatches.filter(isManualBatch);
  const processing = data.recentBatches.filter((batch) => !isManualBatch(batch) && batch.status !== "completed");
  const completed = data.recentBatches.filter((batch) => batch.status === "completed");
  const manualCount = data.tasks.manual ?? data.tasks.review + data.tasks.failed + data.recentBatches.filter((batch) => batch.status === "reference_ready").length;
  const processingCount = data.tasks.processing ?? Math.max(0, data.tasks.waiting + data.tasks.running - data.recentBatches.filter((batch) => batch.status === "reference_ready").length);
  const serviceOnline = Object.values(data.services || {}).some((service) => service.online);
  const codex = data.codex;
  const renderRow = (batch: DashboardSnapshot["recentBatches"][number]) => <button className="batch-work-row" key={batch.id} onClick={() => onOpenBatch(batch.id)}><span className={`batch-status-dot ${batch.status}`} /><span className="batch-work-main"><strong>{batch.name}</strong><small>{batch.error || batch.stage || displayStatus(batch)}</small></span><span className={`batch-state ${batch.status}`}>{displayStatus(batch)}</span><span className="batch-count">{batch.productCount ? `${batch.productCount} 款` : "—"}</span><time>{formatDate(batch.updatedAt || batch.createdAt)}</time></button>;

  return <section className="home-dashboard">
    <header className="workspace-intro"><div><span className="eyebrow">BATCH PRODUCTION WORKSPACE</span><h2>今天要处理什么</h2><p>按优先级处理批次，所有生产任务都从这里继续。</p></div><button className="primary-button dashboard-create" onClick={onCreateBatch}>＋ 新建批次</button></header>
    <section className="work-queue" aria-label="批次工作队列">
      <div className="queue-group queue-manual"><div className="queue-group-head"><div><span className="queue-kicker">优先级 01</span><h3>待人工处理</h3></div><strong>{manualCount}</strong></div><p className="queue-hint">审核、确认或异常任务需要你的决定。</p>{manual.length ? manual.map(renderRow) : <div className="queue-empty">暂无待人工处理批次</div>}</div>
      <div className="queue-group queue-processing"><div className="queue-group-head"><div><span className="queue-kicker">优先级 02</span><h3>生产中</h3></div><strong>{processingCount}</strong></div><p className="queue-hint">正在分析、排片、渲染或等待 Worker。</p>{processing.length ? processing.map(renderRow) : <div className="queue-empty">暂无进行中的批次</div>}</div>
      <div className="queue-group queue-completed"><div className="queue-group-head"><div><span className="queue-kicker">历史记录</span><h3>最近完成</h3></div><strong>{data.tasks.completed}</strong></div><p className="queue-hint">最近交付的批次。</p>{completed.length ? completed.slice(0, 5).map(renderRow) : <div className="queue-empty">暂无已完成批次</div>}</div>
    </section>
    <details className="system-status" open={false}><summary><span>系统状态</span><small>{serviceOnline ? "服务在线" : "服务离线"} · {data.system.queue.running} 个任务处理中</small></summary><div className="system-status-content"><div className="system-status-grid"><div><span>Worker</span><strong>{data.system.worker.online ? "在线" : "离线"}</strong></div><div><span>生产队列</span><strong>等待 {data.system.queue.waiting} · 运行 {data.system.queue.running}</strong></div><div><span>流水线</span><strong>{data.system.pipeline}</strong></div><div><span>渲染完成</span><strong>{data.renderer.completed} 个批次</strong></div></div>{codex && <div className="codex-inline"><span>Codex</span><strong>{codex.status === "auth_invalid" ? "需要重新连接" : codex.status === "unresponsive" ? "暂时无响应" : "可用"}</strong><small>Model Service {codex.modelServiceReachable === true ? "可达" : "未知"} · Executor {codex.codexExecutorAlive === true ? "在线" : "未确认"}</small></div>}<div className="service-queue-grid">{Object.values(data.services || {}).map((service) => <div className="service-queue-card" key={service.name}><div className="service-queue-title"><strong>{service.name}</strong><span>{service.online ? "在线" : service.status === "restarting" ? "重启中" : "离线"}</span></div><div className="service-queue-stats"><span>等待 <b>{service.waiting}</b></span><span>运行 <b>{service.running}</b></span><span>失败 <b>{service.failed}</b></span></div></div>)}</div></div></details>
    <details className="system-status workspace-insights"><summary><span>生产数据与最近任务</span><small>质量门禁、排片结果与历史批次</small></summary><div className="system-status-content"><section className="home-section recent-task-section"><div className="home-section-head"><div><span className="eyebrow">最近任务</span><h3>从这里继续处理</h3></div><button className="icon-button" onClick={onRefresh} aria-label="刷新任务">↻</button></div><div className="recent-tasks-table" role="table"><div className="recent-task-row header" role="row"><span>批次名称</span><span>状态</span><span>产品</span><span>创建时间</span><span>当前进度</span></div>{data.recentBatches.length ? data.recentBatches.map((batch) => <button className="recent-task-row" role="row" key={batch.id} onClick={() => onOpenBatch(batch.id)}><strong>{batch.name}</strong><span>{displayStatus(batch)}</span><span>{batch.productCount ? `${batch.productCount} 款` : "—"}</span><time>{formatDate(batch.createdAt)}</time><span>{batch.error || batch.stage || displayStatus(batch)}</span></button>) : <div className="dashboard-empty">暂无任务。</div>}</div></section><div className="home-secondary-grid"><section className="home-section"><div className="home-section-head"><div><span className="eyebrow">素材质量</span><h3>质量门禁结果</h3></div><strong>{data.quality.accept + data.quality.review + data.quality.reject ? "已有结果" : "等待数据"}</strong></div><div className="quality-summary"><div className="accept"><strong>{data.quality.accept}</strong><span>通过</span></div><div className="review"><strong>{data.quality.review}</strong><span>待确认</span></div><div className="reject"><strong>{data.quality.reject}</strong><span>未通过</span></div></div>{sortHistogram(data.quality.histogram).slice(0, 4).map(([reason, count]) => <div className="reason-list" key={reason}><span>{reason}</span><b>{count}</b></div>)}</section><section className="home-section"><div className="home-section-head"><div><span className="eyebrow">排片结果</span><h3>镜头匹配情况</h3></div><strong>{data.scheduler.success + data.scheduler.failed ? "已有结果" : "等待数据"}</strong></div><div className="schedule-summary"><div><strong>{data.scheduler.success}</strong><span>排片成功</span></div><div><strong>{data.scheduler.failed}</strong><span>需要补镜头</span></div></div></section></div></div></details>
  </section>;
}
